M48
; DRILL file {KiCad 7.0.1} date Thu Aug 17 16:01:54 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-17T16:01:54-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.286
%
G90
G05
T1
X125.7Y-98.305
X132.7Y-98.305
T2
X167.9Y-88.755
X167.9Y-107.805
T0
M30
